// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.canarium.domain;

import ar.edu.um.canarium.domain.ConfiguracionDataOnDemand;
import ar.edu.um.canarium.domain.ConfiguracionIntegrationTest;
import ar.edu.um.canarium.service.ConfiguracionService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConfiguracionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConfiguracionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConfiguracionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConfiguracionIntegrationTest: @Transactional;
    
    @Autowired
    ConfiguracionDataOnDemand ConfiguracionIntegrationTest.dod;
    
    @Autowired
    ConfiguracionService ConfiguracionIntegrationTest.configuracionService;
    
    @Test
    public void ConfiguracionIntegrationTest.testCountAllConfiguracions() {
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", dod.getRandomConfiguracion());
        long count = configuracionService.countAllConfiguracions();
        Assert.assertTrue("Counter for 'Configuracion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConfiguracionIntegrationTest.testFindConfiguracion() {
        Configuracion obj = dod.getRandomConfiguracion();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to provide an identifier", id);
        obj = configuracionService.findConfiguracion(id);
        Assert.assertNotNull("Find method for 'Configuracion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Configuracion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConfiguracionIntegrationTest.testFindAllConfiguracions() {
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", dod.getRandomConfiguracion());
        long count = configuracionService.countAllConfiguracions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Configuracion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Configuracion> result = configuracionService.findAllConfiguracions();
        Assert.assertNotNull("Find all method for 'Configuracion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Configuracion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConfiguracionIntegrationTest.testFindConfiguracionEntries() {
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", dod.getRandomConfiguracion());
        long count = configuracionService.countAllConfiguracions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Configuracion> result = configuracionService.findConfiguracionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Configuracion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Configuracion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConfiguracionIntegrationTest.testFlush() {
        Configuracion obj = dod.getRandomConfiguracion();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to provide an identifier", id);
        obj = configuracionService.findConfiguracion(id);
        Assert.assertNotNull("Find method for 'Configuracion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConfiguracion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Configuracion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfiguracionIntegrationTest.testUpdateConfiguracionUpdate() {
        Configuracion obj = dod.getRandomConfiguracion();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to provide an identifier", id);
        obj = configuracionService.findConfiguracion(id);
        boolean modified =  dod.modifyConfiguracion(obj);
        Integer currentVersion = obj.getVersion();
        Configuracion merged = configuracionService.updateConfiguracion(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Configuracion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConfiguracionIntegrationTest.testSaveConfiguracion() {
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", dod.getRandomConfiguracion());
        Configuracion obj = dod.getNewTransientConfiguracion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Configuracion' identifier to be null", obj.getId());
        try {
            configuracionService.saveConfiguracion(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Configuracion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConfiguracionIntegrationTest.testDeleteConfiguracion() {
        Configuracion obj = dod.getRandomConfiguracion();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Configuracion' failed to provide an identifier", id);
        obj = configuracionService.findConfiguracion(id);
        configuracionService.deleteConfiguracion(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Configuracion' with identifier '" + id + "'", configuracionService.findConfiguracion(id));
    }
    
}
