// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.canarium.domain;

import ar.edu.um.canarium.domain.MensajeDataOnDemand;
import ar.edu.um.canarium.domain.MensajeIntegrationTest;
import ar.edu.um.canarium.service.MensajeService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MensajeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MensajeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MensajeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MensajeIntegrationTest: @Transactional;
    
    @Autowired
    MensajeDataOnDemand MensajeIntegrationTest.dod;
    
    @Autowired
    MensajeService MensajeIntegrationTest.mensajeService;
    
    @Test
    public void MensajeIntegrationTest.testCountAllMensajes() {
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", dod.getRandomMensaje());
        long count = mensajeService.countAllMensajes();
        Assert.assertTrue("Counter for 'Mensaje' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MensajeIntegrationTest.testFindMensaje() {
        Mensaje obj = dod.getRandomMensaje();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to provide an identifier", id);
        obj = mensajeService.findMensaje(id);
        Assert.assertNotNull("Find method for 'Mensaje' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mensaje' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MensajeIntegrationTest.testFindAllMensajes() {
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", dod.getRandomMensaje());
        long count = mensajeService.countAllMensajes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mensaje', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mensaje> result = mensajeService.findAllMensajes();
        Assert.assertNotNull("Find all method for 'Mensaje' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mensaje' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MensajeIntegrationTest.testFindMensajeEntries() {
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", dod.getRandomMensaje());
        long count = mensajeService.countAllMensajes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mensaje> result = mensajeService.findMensajeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mensaje' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mensaje' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MensajeIntegrationTest.testFlush() {
        Mensaje obj = dod.getRandomMensaje();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to provide an identifier", id);
        obj = mensajeService.findMensaje(id);
        Assert.assertNotNull("Find method for 'Mensaje' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMensaje(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Mensaje' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MensajeIntegrationTest.testUpdateMensajeUpdate() {
        Mensaje obj = dod.getRandomMensaje();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to provide an identifier", id);
        obj = mensajeService.findMensaje(id);
        boolean modified =  dod.modifyMensaje(obj);
        Integer currentVersion = obj.getVersion();
        Mensaje merged = mensajeService.updateMensaje(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Mensaje' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MensajeIntegrationTest.testSaveMensaje() {
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", dod.getRandomMensaje());
        Mensaje obj = dod.getNewTransientMensaje(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mensaje' identifier to be null", obj.getId());
        try {
            mensajeService.saveMensaje(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Mensaje' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MensajeIntegrationTest.testDeleteMensaje() {
        Mensaje obj = dod.getRandomMensaje();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mensaje' failed to provide an identifier", id);
        obj = mensajeService.findMensaje(id);
        mensajeService.deleteMensaje(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Mensaje' with identifier '" + id + "'", mensajeService.findMensaje(id));
    }
    
}
