// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.canarium.domain;

import ar.edu.um.canarium.domain.Mensaje;
import ar.edu.um.canarium.domain.MensajeDataOnDemand;
import ar.edu.um.canarium.domain.MensajeTag;
import ar.edu.um.canarium.domain.MensajeTagDataOnDemand;
import ar.edu.um.canarium.domain.Tag;
import ar.edu.um.canarium.domain.TagDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MensajeTagDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MensajeTagDataOnDemand: @Component;
    
    private Random MensajeTagDataOnDemand.rnd = new SecureRandom();
    
    private List<MensajeTag> MensajeTagDataOnDemand.data;
    
    @Autowired
    MensajeDataOnDemand MensajeTagDataOnDemand.mensajeDataOnDemand;
    
    @Autowired
    TagDataOnDemand MensajeTagDataOnDemand.tagDataOnDemand;
    
    public MensajeTag MensajeTagDataOnDemand.getNewTransientMensajeTag(int index) {
        MensajeTag obj = new MensajeTag();
        setMensaje(obj, index);
        setTag(obj, index);
        return obj;
    }
    
    public void MensajeTagDataOnDemand.setMensaje(MensajeTag obj, int index) {
        Mensaje mensaje = mensajeDataOnDemand.getRandomMensaje();
        obj.setMensaje(mensaje);
    }
    
    public void MensajeTagDataOnDemand.setTag(MensajeTag obj, int index) {
        Tag tag = tagDataOnDemand.getRandomTag();
        obj.setTag(tag);
    }
    
    public MensajeTag MensajeTagDataOnDemand.getSpecificMensajeTag(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MensajeTag obj = data.get(index);
        Long id = obj.getId();
        return MensajeTag.findMensajeTag(id);
    }
    
    public MensajeTag MensajeTagDataOnDemand.getRandomMensajeTag() {
        init();
        MensajeTag obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MensajeTag.findMensajeTag(id);
    }
    
    public boolean MensajeTagDataOnDemand.modifyMensajeTag(MensajeTag obj) {
        return false;
    }
    
    public void MensajeTagDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MensajeTag.findMensajeTagEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MensajeTag' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MensajeTag>();
        for (int i = 0; i < 10; i++) {
            MensajeTag obj = getNewTransientMensajeTag(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
