// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.canarium.domain;

import ar.edu.um.canarium.domain.MensajeIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MensajeIntegrationTest_Roo_Configurable {
    
    declare @type: MensajeIntegrationTest: @Configurable;
    
}
