// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.canarium.domain;

import ar.edu.um.canarium.domain.RepublicadoDataOnDemand;
import ar.edu.um.canarium.domain.RepublicadoIntegrationTest;
import ar.edu.um.canarium.service.RepublicadoService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RepublicadoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepublicadoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RepublicadoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RepublicadoIntegrationTest: @Transactional;
    
    @Autowired
    RepublicadoDataOnDemand RepublicadoIntegrationTest.dod;
    
    @Autowired
    RepublicadoService RepublicadoIntegrationTest.republicadoService;
    
    @Test
    public void RepublicadoIntegrationTest.testCountAllRepublicadoes() {
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", dod.getRandomRepublicado());
        long count = republicadoService.countAllRepublicadoes();
        Assert.assertTrue("Counter for 'Republicado' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RepublicadoIntegrationTest.testFindRepublicado() {
        Republicado obj = dod.getRandomRepublicado();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to provide an identifier", id);
        obj = republicadoService.findRepublicado(id);
        Assert.assertNotNull("Find method for 'Republicado' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Republicado' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RepublicadoIntegrationTest.testFindAllRepublicadoes() {
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", dod.getRandomRepublicado());
        long count = republicadoService.countAllRepublicadoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Republicado', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Republicado> result = republicadoService.findAllRepublicadoes();
        Assert.assertNotNull("Find all method for 'Republicado' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Republicado' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RepublicadoIntegrationTest.testFindRepublicadoEntries() {
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", dod.getRandomRepublicado());
        long count = republicadoService.countAllRepublicadoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Republicado> result = republicadoService.findRepublicadoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Republicado' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Republicado' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RepublicadoIntegrationTest.testFlush() {
        Republicado obj = dod.getRandomRepublicado();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to provide an identifier", id);
        obj = republicadoService.findRepublicado(id);
        Assert.assertNotNull("Find method for 'Republicado' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRepublicado(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Republicado' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepublicadoIntegrationTest.testUpdateRepublicadoUpdate() {
        Republicado obj = dod.getRandomRepublicado();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to provide an identifier", id);
        obj = republicadoService.findRepublicado(id);
        boolean modified =  dod.modifyRepublicado(obj);
        Integer currentVersion = obj.getVersion();
        Republicado merged = republicadoService.updateRepublicado(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Republicado' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepublicadoIntegrationTest.testSaveRepublicado() {
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", dod.getRandomRepublicado());
        Republicado obj = dod.getNewTransientRepublicado(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Republicado' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Republicado' identifier to be null", obj.getId());
        try {
            republicadoService.saveRepublicado(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Republicado' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RepublicadoIntegrationTest.testDeleteRepublicado() {
        Republicado obj = dod.getRandomRepublicado();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Republicado' failed to provide an identifier", id);
        obj = republicadoService.findRepublicado(id);
        republicadoService.deleteRepublicado(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Republicado' with identifier '" + id + "'", republicadoService.findRepublicado(id));
    }
    
}
