// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.canarium.domain;

import ar.edu.um.canarium.domain.RepublicadoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RepublicadoDataOnDemand_Roo_Configurable {
    
    declare @type: RepublicadoDataOnDemand: @Configurable;
    
}
